export const FETCHINGREDIENTS = 'FETCHINGREDIENTS'
export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const PROPS_DEFAULT = 'PROPS_DEFAULT'
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'


export const SETINGREDIENTS = 'SETINGREDIENTS'
export const SETINGREDIENTSLOADINGFALSE = 'SETINGREDIENTSLOADINGFALSE'
export const SETLOADINGINGREDIENTSTRUE = 'SETLOADINGINGREDIENTSTRUE'
export const SET_INGREDIENTS_ORDER = 'SET_INGREDIENTS_ORDER'
export const GET_INGREDIENTS_ORDER = 'GET_INGREDIENTSORDER'
export const GET_INGREDIENTS_ORDER_FAILED = 'GET_INGREDIENTSORDERFAILED'


export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_PATH='AUTHPATH'


